site_name: Cocos Documentation
site_url: http://cocos2d-x.org/documentation
site_description: Cocos Documentation.
site_author: The Cocos Teams
pages:
- Home: 'index.md'
- Contents:
    - 'Cocos': 'cocos/cocos.md'
    - 'Manual Installations':
        - 'Prerequisites': 'installation/A.md'
        - 'Android (Terminal) Setup': 'installation/B.md'
        - 'Android (Eclipse) Setup': 'installation/C.md'
        - 'IOS Setup': 'installation/D.md'
        - 'Mac OSX Setup': 'installation/E.md'
        - 'Linux Setup': 'installation/F.md'
        - 'Windows Setup': 'installation/G.md'
        - 'Windows Phone Setup': 'installation/H.md'
    - 'Development Workflows': 'workflows/workflows.md'
    - 'Programmers Guide':
        - 'About Cocos2d-x': 'programmers-guide/1.md'
        - 'Basic Concepts': 'programmers-guide/2.md'
        - 'Sprites': 'programmers-guide/3.md'
        - 'Actions': 'programmers-guide/4.md'
        - 'Scenes': 'programmers-guide/5.md'
        - 'UI': 'programmers-guide/6.md'
        - 'Other Node Types': 'programmers-guide/7.md'
        - 'Event Dispatch': 'programmers-guide/8.md'
        - '3D': 'programmers-guide/9.md'
        - 'Scripting': 'programmers-guide/10.md'
        - 'Physics': 'programmers-guide/11.md'
        - 'Audio': 'programmers-guide/12.md'
        - 'Advanced Topics': 'programmers-guide/13.md'
    - 'Editors & Tools':
        - 'Command-line tool': 'editors_and_tools/cocosCLTool.md'
        - 'Cocos Creator': 'editors_and_tools/creator.md'
        - '_Getting Started': 'editors_and_tools/creator-chapters/getting-started/index.md'
        - '_Introduction': 'editors_and_tools/creator-chapters/getting-started/introduction.md'
        - '_Install': 'editors_and_tools/creator-chapters/getting-started/install.md'
        - '_Dashboard': 'editors_and_tools/creator-chapters/getting-started/dashboard.md'
        - '_Hello World': 'editors_and_tools/creator-chapters/getting-started/hello-world.md'
        - '_Quick Start': 'editors_and_tools/creator-chapters/getting-started/quick-start.md'
        - '_Cocos2d-x Guide': 'editors_and_tools/creator-chapters/getting-started/cocos2d-x-guide.md'
        - '_Unity Guide': 'editors_and_tools/creator-chapters/getting-started/unity-guide.md'
        - '_Project Structure': 'editors_and_tools/creator-chapters/getting-started/project-structure.md'
        - '_Support': 'editors_and_tools/creator-chapters/getting-started/support.md'
        - '_Getting Started': 'editors_and_tools/creator-chapters/basics/index.md'
        - '_Editor Overview': 'editors_and_tools/creator-chapters/basics/editor-overview.md'
        - '_Assets': 'editors_and_tools/creator-chapters/basics/editor-panels/assets.md'
        - '_Scene': 'editors_and_tools/creator-chapters/basics/editor-panels/scene.md'
        - '_Hierarchy': 'editors_and_tools/creator-chapters/basics/editor-panels/hierarchy.md'
        - '_Inspector': 'editors_and_tools/creator-chapters/basics/editor-panels/inspector.md'
        - '_Console': 'editors_and_tools/creator-chapters/basics/editor-panels/console.md'
        - '_Toolbar': 'editors_and_tools/creator-chapters/basics/toolbar.md'
        - '_Layout': 'editors_and_tools/creator-chapters/basics/layout.md'
        - '_Preview Build': 'editors_and_tools/creator-chapters/basics/preview-build.md'
        - '_Getting Started': 'editors_and_tools/creator-chapters/asset-workflow/index.md'
        - '_Scene Managing': 'editors_and_tools/creator-chapters/asset-workflow/scene-managing.md'
        - '_Sprite': 'editors_and_tools/creator-chapters/asset-workflow/sprite.md'
        - '_Atlas': 'editors_and_tools/creator-chapters/asset-workflow/atlas.md'
        - '_Font': 'editors_and_tools/creator-chapters/asset-workflow/font.md'
        - '_Particle': 'editors_and_tools/creator-chapters/asset-workflow/particle.md'
        - '_Audio Asset': 'editors_and_tools/creator-chapters/asset-workflow/audio-asset.md'
        - '_Prefab': 'editors_and_tools/creator-chapters/asset-workflow/prefab.md'
        - '_Getting Started': 'editors_and_tools/creator-chapters/content-workflow/index.md'
        - '_Node Component': 'editors_and_tools/creator-chapters/content-workflow/node-component.md'
        - '_Transform': 'editors_and_tools/creator-chapters/content-workflow/transform.md'
        - '_Node Tree': 'editors_and_tools/creator-chapters/content-workflow/node-tree.md'
        - '_Scene Editing': 'editors_and_tools/creator-chapters/content-workflow/scene-editing.md'
        - '_Getting Started': 'editors_and_tools/creator-chapters/ui/index.md'
        - '_Sliced Sprite': 'editors_and_tools/creator-chapters/ui/sliced-sprite.md'
        - '_Multi-Resolution': 'editors_and_tools/creator-chapters/ui/multi-resolution.md'
        - '_Widget Align': 'editors_and_tools/creator-chapters/ui/widget-align.md'
        - '_Label Layout': 'editors_and_tools/creator-chapters/ui/label-layout.md'
        - '_UI Components': 'editors_and_tools/creator-chapters/ui/ui-components.md'
        - '_Auto Layout': 'editors_and_tools/creator-chapters/ui/auto-layout.md'
        - '_List With Data': 'editors_and_tools/creator-chapters/ui/list-with-data.md'
        - '_Getting Started': 'editors_and_tools/creator-chapters/animation/index.md'
        - '_Animation': 'editors_and_tools/creator-chapters/animation/animation.md'
        - '_Animation Clip': 'editors_and_tools/creator-chapters/animation/animation-clip.md'
        - '_Animation Curve': 'editors_and_tools/creator-chapters/animation/animation-curve.md'
        - '_Sprite Animation': 'editors_and_tools/creator-chapters/animation/sprite-animation.md'
        - '_Time Curve': 'editors_and_tools/creator-chapters/animation/time-curve.md'
        - '_Animation Event': 'editors_and_tools/creator-chapters/animation/animation-event.md'
        - '_Scripting Animation': 'editors_and_tools/creator-chapters/animation/scripting-animation.md'
        - '_Getting Started': 'editors_and_tools/creator-chapters/components/index.md'
        - '_Sprite': 'editors_and_tools/creator-chapters/components/sprite.md'
        - '_Label': 'editors_and_tools/creator-chapters/components/label.md'
        - '_Animation': 'editors_and_tools/creator-chapters/components/animation.md'
        - '_Canvas': 'editors_and_tools/creator-chapters/components/canvas.md'
        - '_Widget': 'editors_and_tools/creator-chapters/components/widget.md'
        - '_Progress': 'editors_and_tools/creator-chapters/components/progress.md'
        - '_Button': 'editors_and_tools/creator-chapters/components/button.md'
        - '_Mask': 'editors_and_tools/creator-chapters/components/mask.md'
        - '_Scrollview': 'editors_and_tools/creator-chapters/components/scrollview.md'
        - '_Scrollbar': 'editors_and_tools/creator-chapters/components/scrollbar.md'
        - '_Layout': 'editors_and_tools/creator-chapters/components/layout.md'
        - '_Getting Started': 'editors_and_tools/creator-chapters/scripting/index.md'
        - '_Use Component': 'editors_and_tools/creator-chapters/scripting/use-component.md'
        - '_Properties': 'editors_and_tools/creator-chapters/scripting/properties.md'
        - '_Access Node Component': 'editors_and_tools/creator-chapters/scripting/access-node-component.md'
        - '_Life Cycle Callbacks': 'editors_and_tools/creator-chapters/scripting/life-cycle-callbacks.md'
        - '_Create Destroy': 'editors_and_tools/creator-chapters/scripting/create-destroy.md'
        - '_Events': 'editors_and_tools/creator-chapters/scripting/events.md'
        - '_Internal Events': 'editors_and_tools/creator-chapters/scripting/internal-events.md'
        - '_Actions': 'editors_and_tools/creator-chapters/scripting/actions.md'
        - '_Action List': 'editors_and_tools/creator-chapters/scripting/action-list.md'
        - '_Scheduler': 'editors_and_tools/creator-chapters/scripting/scheduler.md'
        - '_Execution Order': 'editors_and_tools/creator-chapters/scripting/execution-order.md'
        - '_Network': 'editors_and_tools/creator-chapters/scripting/network.md'
        - '_Pooling': 'editors_and_tools/creator-chapters/scripting/pooling.md'
        - '_Load Assets': 'editors_and_tools/creator-chapters/scripting/load-assets.md'
        - '_Modular Script': 'editors_and_tools/creator-chapters/scripting/modular-script.md'
        - '_Third Party Module': 'editors_and_tools/creator-chapters/scripting/third-party-module.md'
        - '_Web Debug Scripts': 'editors_and_tools/creator-chapters/scripting/web-debug-scripts.md'
        - '_JavaScript Primer': 'editors_and_tools/creator-chapters/scripting/javascript-primer.md'
        - '_Attributes': 'editors_and_tools/creator-chapters/scripting/attributes.md'
        - '_Coding Standards': 'editors_and_tools/creator-chapters/scripting/coding-standards.md'
        - '_Size Provider': 'editors_and_tools/creator-chapters/scripting/size-provider.md'
        - '_Getting Started': 'editors_and_tools/creator-chapters/publish/index.md'
        - '_Publish --> Web': 'editors_and_tools/creator-chapters/publish/publish-web.md'
        - '_Cocos Framework': 'editors_and_tools/creator-chapters/publish/cocos-framework.md'
        - '_Publish --> Native': 'editors_and_tools/creator-chapters/publish/publish-native.md'
        - '_Extensions': 'editors_and_tools/creator-chapters/extension/index.md'
        - 'Cocos Studio': 'editors_and_tools/studio.md'
        - '_Workspace_Overview': 'editors_and_tools/studio-chapters/Workspace_Overview/en.md'
        - '_CodeAndDebug': 'editors_and_tools/studio-chapters/chapter2/CodeAndDebug/en.md'
        - '_PackageAndRun': 'editors_and_tools/studio-chapters/chapter2/PackageAndRun/en.md'
        - '_Publish': 'editors_and_tools/studio-chapters/chapter2/Publish/en.md'
        - '_SceneAndLayer': 'editors_and_tools/studio-chapters/chapter2/SceneAndLayer/en.md'
        - '_SpriteSheet': 'editors_and_tools/studio-chapters/chapter2/SpriteSheet/en.md'
        - '_Basic Objects': 'editors_and_tools/studio-chapters/chapter3/UI/BasicObjects/en.md'
        - '_Widgets': 'editors_and_tools/studio-chapters/chapter3/UI/Widgets/en.md'
        - '_Containers': 'editors_and_tools/studio-chapters/chapter3/UI/Containers/en.md'
        - '_Armature': 'editors_and_tools/studio-chapters/chapter3/UI/Armature/en.md'
        - '_UI Layout and Multi-resolution Support': 'editors_and_tools/studio-chapters/chapter3/UI/Layout/en.md'
        - '_9-Slice': 'editors_and_tools/studio-chapters/chapter3/UI/9Slice/en.md'
        - '_Rulers and Guides': 'editors_and_tools/studio-chapters/chapter3/UI/RulersGuides/en.md'
        - '_Create 2D SpriteSheet Animation': 'editors_and_tools/studio-chapters/chapter3/Animation/2DSpriteSheetAnimation/en.md'
        - '_Key Frames': 'editors_and_tools/studio-chapters/chapter3/Animation/InsertKeyframe/en.md'
        - '_Create a Frame Event': 'editors_and_tools/studio-chapters/chapter3/Animation/AddFrameEvents/en.md'
        - '_Create a Skeletal Animation': 'editors_and_tools/studio-chapters/chapter3/Animation/CreateSkeletalAnimation/en.md'
        - '_Edit Skeletal Animation': 'editors_and_tools/studio-chapters/chapter3/Animation/EditSkeletalAnimation/en.md'
        - '_How to -> Create a Skeletal Animation with cocos': 'editors_and_tools/studio-chapters/chapter3/Animation/Sample/en.md'
        - '_Use Skeletal Animation': 'editors_and_tools/studio-chapters/chapter3/Animation/UseSkeletalAnimation/en.md'
        - '_Create 3D Scenes': 'editors_and_tools/studio-chapters/chapter3/3D/New3DScene/en.md'
        - '_3D Model Overview': 'editors_and_tools/studio-chapters/chapter3/3D/3DModel/en.md'
        - '_3D Particles Overview': 'editors_and_tools/studio-chapters/chapter3/3D/3DParticle/en.md'
        - '_Camera': 'editors_and_tools/studio-chapters/chapter3/3D/Camera/en.md'
        - '_3D Keyboard Shortcuts': 'editors_and_tools/studio-chapters/chapter3/3D/3DShortcutKey/en.md'
        - '_3D Node Overview': 'editors_and_tools/studio-chapters/chapter3/3D/3DNode/en.md'
        - '_SkyBox': 'editors_and_tools/studio-chapters/chapter3/3D/SkyBox/en.md'
        - '_Light': 'editors_and_tools/studio-chapters/chapter3/3D/Light/en.md'
        - '_Widgets Extension': 'editors_and_tools/studio-chapters/chapter3/Extend/WidgetExtend/en.md'
        - '_Properties Extension': 'editors_and_tools/studio-chapters/chapter3/Extend/ParamExtend/en.md'
        - '_Customizing Exported Data Formats': 'editors_and_tools/studio-chapters/chapter3/Extend/CustomExport/en.md'
        - '_Samples': 'editors_and_tools/studio-chapters/chapter3/Extend/Sample/en.md'
        - '_Callback Feature': 'editors_and_tools/studio-chapters/chapter3/HowToCode/CallBack/en.md'
        - '_Create Custom Data': 'editors_and_tools/studio-chapters/chapter3/HowToCode/UserData/en.md'
        - '_Load Exported Data': 'editors_and_tools/studio-chapters/chapter3/HowToCode/LoadExportData/en.md'
        - '_Customize Cocos Framework & Simulator': 'editors_and_tools/studio-chapters/chapter3/HowToCode/CustomizeFramework-v3.10/en.md'
        - '_1 No Android Devices Found': 'editors_and_tools/studio-chapters/chapter4/connect-solution/en.md'
        - '_2 How to -> Debug Browser Preview': 'editors_and_tools/studio-chapters/chapter4/debug-on-browser/en.md'
        - '_3 How to -> Use CCLog to Debug project based on precompiled library': 'editors_and_tools/studio-chapters/chapter4/FWNoLog/en.md'
        - '_4 How to -> Use FBX File': 'editors_and_tools/studio-chapters/chapter4/HowToUseFBX/en.md'
        - '_5 How to -> Load SpriteSheet Correctly': 'editors_and_tools/studio-chapters/chapter4/OnePixelBug/en.md'
        - '_6 How to -> Preload Resources': 'editors_and_tools/studio-chapters/chapter4/PreloadRes/en.md'
        - '_7 How to -> Automatically Wrap Text and Adjust Height of Text': 'editors_and_tools/studio-chapters/chapter4/TextAuto/en.md'
        - '_8 Two Automatic Recursive Function on UIHelper': 'editors_and_tools/studio-chapters/chapter4/UIHelperGetNode/en.md'
        - '_9 Issues about Upgrading or Downgrading Framework': 'editors_and_tools/studio-chapters/chapter4/upgrade-framework/en.md'
        - '_10 How to -> Load Data Exported from cocos': 'editors_and_tools/studio-chapters/chapter4/LoadError/en.md'
        - '_11 How to -> Import Project from v1.6': 'editors_and_tools/studio-chapters/chapter4/Import1.6ProjectError/en.md'
        - '_12 Customize Framework(v3.7)': 'editors_and_tools/studio-chapters/chapter3/HowToCode/CustomizeFramework/en.md'
        - '_13 Customize Framework(v3.8~3.9)': 'editors_and_tools/studio-chapters/chapter3/HowToCode/CustomizeFramework-v3.8/en.md'
        - '_14 Customize precompiled library(v3.10)': 'editors_and_tools/studio-chapters/chapter3/HowToCode/CustomizeFramework-v3.10/en.md'
        - '_15 How to -> Fix Packaging and Running Issues': 'editors_and_tools/studio-chapters/chapter4/FixPackageError/en.md'
        - '_16 How to -> Simplify Widgets Initial Resources': 'editors_and_tools/studio-chapters/chapter4/SimplifyWidgetsRes/en.md'
        - '_17 How to -> Run Previous Versions of Addins in cocos': 'editors_and_tools/studio-chapters/chapter4/PluginLoadError/en.md'
        - '_18 How to -> Fix cocos Run Error?': 'editors_and_tools/studio-chapters/chapter4/runError/en.md'
    - 'Services':
        - 'SDKBOX': 'services/sdkbox.md'
    - 'Tutorials':
        - 'JavaScript': 'tutorials/javascript/javascript.md'
        - '_Chapter2': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter2/en.md'
        - '_Chapter3': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter3/en.md'
        - '_Chapter4': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter4/en.md'
        - '_Chapter5': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter5/en.md'
        - '_Chapter6': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter6/en.md'
        - '_Chapter7': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter7/en.md'
        - '_Chapter8': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter8/en.md'
        - '_Chapter9': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter9/en.md'
        - '_Chapter10': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter10/en.md'
    - 'API Reference': 'api-ref/index.md'
#- About: 'title.md'

#theme: readable
theme_dir: 'theme'
copyright: Copyright (c) 2014-2016 Chukong Technologies Inc.
use_directory_urls: false
repo_url: https://github.com/chukong/cocos-docs
repo_name: GitHub
google_analytics: ['UA-3216502-3', 'Cocos2d-x.org']
